import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { Plus, Edit2, Trash2, MapPin, Save, X, RefreshCw, Search, Layers } from 'lucide-react';
import './App.css';

const API_URL = 'http://localhost:5000/api/landmarks'; // Ensure this matches your backend port

const CATEGORIES = ['Admin', 'Tech', 'Sports', 'Housing', 'Academic', 'Entrance', 'Venue', 'Facilities', 'Health'];

export default function AdminDashboard() {
  // --- 1. STATE DECLARATIONS (Must all be at the top) ---
  const [landmarks, setLandmarks] = useState([]);
  const [loading, setLoading] = useState(true);
  
  // Search & Filter State
  const [searchQuery, setSearchQuery] = useState('');
  const [filterCategory, setFilterCategory] = useState('All');

  // Form State
  const [editingId, setEditingId] = useState(null);
  const [formData, setFormData] = useState({ 
    name: '', 
    lat: '', 
    lng: '', 
    category: 'Academic', 
    floorInfo: '' 
  });

  // --- 2. API FUNCTIONS ---
  // Fetch data on load
  const fetchLandmarks = async () => {
    setLoading(true);
    try {
      const res = await axios.get(API_URL);
      setLandmarks(res.data);
    } catch (err) {
      console.error("Error fetching landmarks:", err);
      alert("Make sure your backend server is running on port 5000!");
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchLandmarks();
  }, []);

  // --- 3. FORM HANDLERS ---
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const resetForm = () => {
    setEditingId(null);
    setFormData({ name: '', lat: '', lng: '', category: 'Academic', floorInfo: '' });
  };

  const handleEdit = (loc) => {
    setEditingId(loc.id);
    setFormData({ 
      name: loc.name, 
      lat: loc.lat, 
      lng: loc.lng, 
      category: loc.category, 
      floorInfo: loc.floorInfo || '' 
    });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      // Ensure coordinates are numbers
      const payload = {
        ...formData,
        lat: parseFloat(formData.lat),
        lng: parseFloat(formData.lng)
      };

      if (editingId) {
        // Update existing
        await axios.put(`${API_URL}/${editingId}`, payload);
      } else {
        // Create new (ID is auto-generated by backend)
        await axios.post(API_URL, payload);
      }
      
      resetForm();
      fetchLandmarks();
    } catch (err) {
      console.error("Error saving landmark:", err);
      alert("Failed to save. Check console for errors.");
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm("Are you sure you want to delete this landmark?")) return;
    try {
      await axios.delete(`${API_URL}/${id}`);
      fetchLandmarks();
    } catch (err) {
      console.error("Error deleting:", err);
    }
  };

  // --- 4. FILTER LOGIC ---
  const filteredLandmarks = landmarks.filter(loc => {
    const matchesSearch = loc.name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = filterCategory === 'All' || loc.category === filterCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <div className="min-h-screen bg-gray-900 text-gray-200 flex flex-col font-sans selection:bg-purple-500/30">
      
      {/* Top Navbar */}
      <nav className="bg-black border-b border-purple-900/50 text-white p-4 shadow-lg flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-center space-x-3">
          <div className="bg-purple-600/20 p-2 rounded-lg border border-purple-500/30">
            <MapPin size={24} className="text-purple-400" />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-wide text-white">
              SECE Smart Navigator
            </h1>
            <p className="text-xs font-medium text-purple-400 uppercase tracking-widest">
              Database Admin Panel
            </p>
          </div>
        </div>
        <div className="bg-gray-800 px-4 py-2 rounded-full border border-gray-700 text-gray-300 text-sm font-medium flex items-center shadow-inner">
          <span className="w-2 h-2 rounded-full bg-purple-500 mr-2 animate-pulse"></span>
          Total Landmarks: <span className="font-bold text-white ml-1">{landmarks.length}</span>
        </div>
      </nav>

      <div className="flex-1 max-w-7xl w-full mx-auto p-4 sm:p-6 grid grid-cols-1 lg:grid-cols-3 gap-6 lg:gap-8">
        
        {/* LEFT COLUMN: Data Entry Form */}
        <div className="lg:col-span-1">
          <div className="bg-gray-800 rounded-2xl shadow-xl border border-gray-700 p-5 sm:p-6 sticky top-6">
            <h2 className="text-lg font-bold text-white mb-5 flex items-center border-b border-gray-700 pb-3">
              {editingId ? <Edit2 size={18} className="mr-2 text-purple-400"/> : <Plus size={18} className="mr-2 text-purple-400"/>}
              {editingId ? 'Edit Landmark Data' : 'Add New Landmark'}
            </h2>

            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase mb-1 tracking-wider">Landmark Name</label>
                <input 
                  type="text" name="name" required
                  value={formData.name} onChange={handleInputChange}
                  className="w-full p-3 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition-all text-white placeholder-gray-600"
                  placeholder="e.g., Central Library"
                />
              </div>
              
              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase mb-1 tracking-wider">Floor / Location Details (Optional)</label>
                <input 
                  type="text" name="floorInfo"
                  value={formData.floorInfo} onChange={handleInputChange}
                  className="w-full p-3 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition-all text-white placeholder-gray-600"
                  placeholder="e.g., 3rd Floor"
                />
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-gray-400 uppercase mb-1 tracking-wider">Latitude</label>
                  <input 
                    type="number" step="any" name="lat" required
                    value={formData.lat} onChange={handleInputChange}
                    className="w-full p-3 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition-all text-white placeholder-gray-600"
                    placeholder="10.827..."
                  />
                </div>
                <div>
                  <label className="block text-xs font-bold text-gray-400 uppercase mb-1 tracking-wider">Longitude</label>
                  <input 
                    type="number" step="any" name="lng" required
                    value={formData.lng} onChange={handleInputChange}
                    className="w-full p-3 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition-all text-white placeholder-gray-600"
                    placeholder="77.060..."
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase mb-1 tracking-wider">Category</label>
                <select 
                  name="category" required
                  value={formData.category} onChange={handleInputChange}
                  className="w-full p-3 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 outline-none transition-all text-white appearance-none"
                >
                  {CATEGORIES.map(cat => <option key={cat} value={cat}>{cat}</option>)}
                </select>
              </div>

              <div className="pt-4 flex space-x-3">
                <button type="submit" className="flex-1 bg-purple-600 hover:bg-purple-700 text-white font-bold py-3 px-4 rounded-xl flex justify-center items-center transition-all shadow-[0_0_15px_rgba(147,51,234,0.3)] hover:shadow-[0_0_25px_rgba(147,51,234,0.5)]">
                  <Save size={18} className="mr-2" /> {editingId ? 'Update Location' : 'Save Location'}
                </button>
                {editingId && (
                  <button type="button" onClick={resetForm} className="bg-gray-700 hover:bg-gray-600 text-gray-300 font-bold py-3 px-4 rounded-xl transition-colors border border-gray-600">
                    <X size={18} />
                  </button>
                )}
              </div>
            </form>
          </div>
        </div>

        {/* RIGHT COLUMN: Data Table */}
        <div className="lg:col-span-2 flex flex-col">
          <div className="bg-gray-800 rounded-2xl shadow-xl border border-gray-700 overflow-hidden flex flex-col flex-1">
            
            <div className="p-4 sm:p-5 border-b border-gray-700 bg-gray-800/50 flex justify-between items-center">
              <h2 className="text-lg font-bold text-white flex items-center">
                <Layers size={18} className="mr-2 text-purple-400"/>
                Managed Locations
              </h2>
              <button onClick={fetchLandmarks} className="text-gray-400 hover:text-purple-400 flex items-center text-sm font-semibold transition-colors bg-gray-900 px-3 py-1.5 rounded-lg border border-gray-700">
                <RefreshCw size={14} className={`mr-2 ${loading ? 'animate-spin' : ''}`} /> Refresh
              </button>
            </div>

            {/* Search and Filter Controls */}
            <div className="p-4 border-b border-gray-700 flex flex-col sm:flex-row gap-4 bg-gray-900/30">
              <div className="flex-1 relative">
                <Search className="absolute left-3 top-3 text-gray-500" size={18} />
                <input 
                  type="text" 
                  placeholder="Search landmarks by name..." 
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full pl-10 pr-4 py-2.5 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 outline-none transition-all text-sm text-white placeholder-gray-500"
                />
              </div>
              <div className="sm:w-56">
                <select 
                  value={filterCategory}
                  onChange={(e) => setFilterCategory(e.target.value)}
                  className="w-full p-2.5 bg-gray-900 border border-gray-700 rounded-xl focus:ring-2 focus:ring-purple-500 outline-none transition-all text-sm text-white appearance-none"
                >
                  <option value="All">All Categories</option>
                  {CATEGORIES.map(cat => <option key={`filter-${cat}`} value={cat}>{cat}</option>)}
                </select>
              </div>
            </div>

            {/* Responsive Table Container */}
            <div className="overflow-x-auto flex-1 bg-gray-800">
              <table className="w-full text-left border-collapse min-w-[600px]">
                <thead>
                  <tr className="bg-black text-gray-400 text-xs uppercase tracking-wider">
                    <th className="p-4 font-bold border-b border-gray-700 w-16">ID</th>
                    {/* Fixed Header text to reflect the floor info! */}
                    <th className="p-4 font-bold border-b border-gray-700">Name & Details</th> 
                    <th className="p-4 font-bold border-b border-gray-700">Category</th>
                    <th className="p-4 font-bold border-b border-gray-700">Coordinates</th>
                    <th className="p-4 font-bold border-b border-gray-700 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="text-sm text-gray-300">
                  {filteredLandmarks.length === 0 && !loading && (
                    <tr>
                      <td colSpan="5" className="p-12 text-center text-gray-500 flex-col items-center">
                        <MapPin size={48} className="mx-auto mb-4 opacity-20" />
                        <p>No landmarks found matching your criteria.</p>
                      </td>
                    </tr>
                  )}
                  {filteredLandmarks.map((loc) => (
                    <tr key={loc.id} className="border-b border-gray-700 hover:bg-gray-700/50 transition-colors">
                      <td className="p-4 font-mono font-bold text-purple-400">#{loc.id}</td>
                      <td className="p-4">
                        <div className="font-bold text-white">{loc.name}</div>
                        {/* Now floorInfo renders correctly inside the table! */}
                        {loc.floorInfo && (
                          <div className="text-xs text-gray-400 mt-0.5">📍 {loc.floorInfo}</div>
                        )}
                      </td>
                      <td className="p-4">
                        <span className="bg-gray-900 text-purple-300 border border-purple-500/30 px-3 py-1 rounded-full text-xs font-semibold tracking-wide">
                          {loc.category}
                        </span>
                      </td>
                      <td className="p-4 text-xs font-mono text-gray-500">
                        {loc.lat.toFixed(5)},<br className="sm:hidden" /> <span className="hidden sm:inline"> </span>
                        {loc.lng.toFixed(5)}
                      </td>
                      <td className="p-4 text-right space-x-2">
                        <button 
                          onClick={() => handleEdit(loc)}
                          className="inline-flex items-center justify-center p-2 bg-gray-700 text-purple-400 hover:bg-purple-600 hover:text-white rounded-lg transition-colors border border-gray-600 hover:border-purple-500"
                          title="Edit"
                        >
                          <Edit2 size={16} />
                        </button>
                        <button 
                          onClick={() => handleDelete(loc.id)}
                          className="inline-flex items-center justify-center p-2 bg-gray-700 text-red-400 hover:bg-red-600 hover:text-white rounded-lg transition-colors border border-gray-600 hover:border-red-500"
                          title="Delete"
                        >
                          <Trash2 size={16} />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            
          </div>
        </div>

      </div>
    </div>
  );
}